const uiText = {
  en: {
    skipToContent: 'Skip to content', insightsNav: 'Insights', labsHeading: 'Put architecture into practice.', resultsCount: '{count} questions available', dumpsSource: 'DumpsBase: unofficial practice set',
    learn: 'Learn', exam: 'Exam mode', sources: 'Sources', reset: 'Reset progress', theme: 'Theme', language: 'Language', auto: 'Auto', light: 'Light', dark: 'Dark', contrast: 'High contrast', start: 'Start learning', updated: 'Updated for the 2026 study guide',
    heroIntro: 'A focused, source-led practice environment for AB-100. Learn the decision behind the answer, not just the letter.', reviewed: 'questions reviewed', studyDesk: 'Your study desk', choose: 'Choose your angle.', confidence: 'Build confidence in layers.', carry: 'Start with the concepts that carry the most weight.',
    learnTopic: 'Learn by topic', learnTopicDesc: 'Short explanations, source links, and all the reasoning behind each answer.', openTopic: 'Open topic view', examSim: 'Exam simulation', examDesc: 'Timed, clean, and intentionally uncomfortable. See your score at the end.', startRun: 'Start 20-question run', review: 'Review weak spots', reviewDesc: 'Return to the questions you missed or have not answered yet.', reviewNow: 'Review now',
    coursePath: 'Course path', buildPath: 'Build the path.', labs: 'Hands-on labs', allDomains: 'All three domains', question: 'Question', source: 'Source', close: 'Close', related: 'Related lab', openLab: 'Open lab brief', noMatch: 'No questions match this search.', minutes: 'min left', complete: 'Exam complete', correct: 'correct', previous: 'Previous', next: 'Next question', finish: 'Finish', courseware: 'Courseware insights', readInsight: 'Read insight', checklist: 'Checklist', artifacts: 'Artifacts', originalLab: 'Open original lab', originalCourseware: 'Original courseware source', verificationSource: 'Read the verification source',
    checkAnswer: 'Check answer', retryAnswer: 'Try again', chooseAnswer: 'Choose', correctAnswer: 'Correct answer', finishExam: 'Finish exam', abortExam: 'Abort exam', abortConfirm: 'Abort this exam? Its responses will be discarded. Learning progress will not change.', resetConfirm: 'Reset all study and lab progress, backups, and the current exam? Theme and language will be kept.', noWeakSpots: 'No weak spots. All questions have been answered correctly.', storageWarning: 'Some saved data is unavailable or incompatible. You can continue, but changes may be kept only for this visit.',
    title: 'AB-100 Field Guide', description: 'Interactive field guide for Microsoft AB-100 Agentic AI Business Solutions Architect.', home: 'AB-100 Field Guide home', badge: 'Microsoft Certified Expert badge', navigation: 'Main navigation', chooseTheme: 'Choose color theme', chooseLanguage: 'Choose language', heroLead: 'Architect agentic AI', heroEnd: 'business solutions.', studyProgress: 'Study progress', questionProgress: 'Question progress', mastery: 'progress', of: 'of', courseCaption: '9 labs, Contoso Service Resolution Accelerator', insightHeading: 'Concepts worth carrying into production.', labFilter: 'Filter labs by domain', practiceBank: 'Practice bank', search: 'Search questions and concepts', searchPlaceholder: 'Search concepts...', topicFilter: 'Topic filter', allTopics: 'All topics', questionList: 'Question list', evidence: 'Evidence over folklore', sourceLead: 'Start with the', sourceEnd: 'source of truth.', studyGuide: 'Official exam study guide', skillsScope: 'Skills measured, weights, and scope ↗', learnPath: 'Architect AI solutions for business productivity', learnPathNote: 'Microsoft Learn training path ↗', unofficialSet: 'Unofficial practice set', usedCritically: 'Used critically ↗', footerNote: 'Built for deliberate practice · Complete legal details before publication', legalInformation: 'Legal information', disclaimer: 'Disclaimer', privacy: 'Privacy', imprint: 'Legal Notice', closeDialog: 'Close dialog', legalNotes: 'Legal notes', labNotes: 'Lab brief', insightNotes: 'Courseware insight', studyArea: 'Study this area', connectedLabs: '{count} connected labs', lab: 'Lab', plan: 'Plan', design: 'Design', deploy: 'Deploy', status: 'Status', learnSource: 'Read Microsoft Learn source', confirmed: 'confirmed', partiallyConfirmed: 'partially confirmed', unofficial: 'Unofficial practice, Learn-aligned', verification: 'Documentation-reviewed; scenario judgment, not a product execution test', labVerification: 'Courseware-derived; verify against Microsoft Learn', localeWarning: 'A current German translation is unavailable for some content. Those records are shown in English; answer state is unchanged.', examUnavailable: 'An exam requires at least 20 unique questions.', resourceLabs: 'Architecture labs ↗', resourceGuide: 'Learning guide ↗', resourceOfficial: 'Microsoft Learn source ↗'
  },
  de: {
    skipToContent: 'Zum Inhalt springen', insightsNav: 'Erkenntnisse', labsHeading: 'Architektur praktisch erproben.', resultsCount: '{count} Fragen verfügbar', dumpsSource: 'DumpsBase: inoffizielle Übungssammlung',
    learn: 'Lernen', exam: 'Prüfungsmodus', sources: 'Quellen', reset: 'Fortschritt zurücksetzen', theme: 'Darstellung', language: 'Sprache', auto: 'Automatisch', light: 'Hell', dark: 'Dunkel', contrast: 'Hoher Kontrast', start: 'Lernen starten', updated: 'Aktualisiert für den Study Guide 2026',
    heroIntro: 'Eine fokussierte, quellenbasierte Lernumgebung für AB-100. Verstehe die Entscheidung hinter der Antwort, nicht nur den Buchstaben.', reviewed: 'Fragen bearbeitet', studyDesk: 'Dein Lernbereich', choose: 'Wähle deinen Einstieg.', confidence: 'Sicherheit Schritt für Schritt aufbauen.', carry: 'Beginne mit den Konzepten mit der höchsten Prüfungsrelevanz.',
    learnTopic: 'Nach Thema lernen', learnTopicDesc: 'Kurze Erklärungen, Quellenlinks und die Begründung hinter jeder Antwort.', openTopic: 'Themenansicht öffnen', examSim: 'Prüfungssimulation', examDesc: 'Mit Zeitlimit und ohne Hilfestellung. Die Auswertung erfolgt am Ende.', startRun: '20-Fragen-Durchlauf starten', review: 'Schwachstellen wiederholen', reviewDesc: 'Bearbeite falsch oder noch nicht beantwortete Fragen erneut.', reviewNow: 'Jetzt wiederholen',
    coursePath: 'Lernpfad', buildPath: 'Baue deinen Lernpfad.', labs: 'Praxis-Labs', allDomains: 'Alle drei Bereiche', question: 'Frage', source: 'Quelle', close: 'Schließen', related: 'Verwandtes Lab', openLab: 'Lab-Kurzbeschreibung öffnen', noMatch: 'Keine Fragen passen zu dieser Suche.', minutes: 'Min. übrig', complete: 'Prüfung abgeschlossen', correct: 'richtig', previous: 'Zurück', next: 'Nächste Frage', finish: 'Beenden', courseware: 'Erkenntnisse aus dem Kursmaterial', readInsight: 'Erkenntnis lesen', checklist: 'Checkliste', artifacts: 'Arbeitsergebnisse', originalLab: 'Original-Lab öffnen', originalCourseware: 'Originalquelle des Kursmaterials', verificationSource: 'Belegquelle lesen',
    checkAnswer: 'Antwort prüfen', retryAnswer: 'Erneut versuchen', chooseAnswer: 'Auswählen', correctAnswer: 'Richtige Antwort', finishExam: 'Prüfung abschließen', abortExam: 'Prüfung abbrechen', abortConfirm: 'Diese Prüfung abbrechen? Deine Antworten werden verworfen. Der Lernfortschritt bleibt erhalten.', resetConfirm: 'Lernfortschritt, Lab-Fortschritt, Sicherungen und die aktuelle Prüfung zurücksetzen? Darstellung und Sprache bleiben erhalten.', noWeakSpots: 'Keine Schwachstellen. Alle Fragen wurden richtig beantwortet.', storageWarning: 'Einige gespeicherte Daten sind nicht verfügbar oder nicht kompatibel. Du kannst fortfahren, aber Änderungen bleiben möglicherweise nur für diesen Besuch erhalten.',
    title: 'AB-100 Lernbegleiter', description: 'Interaktiver Lernbegleiter für Microsoft AB-100 Agentic AI Business Solutions Architect.', home: 'AB-100 Lernbegleiter: Startseite', badge: 'Microsoft Certified Expert-Abzeichen', navigation: 'Hauptnavigation', chooseTheme: 'Farbdarstellung wählen', chooseLanguage: 'Sprache wählen', heroLead: 'Agentische KI für', heroEnd: 'Geschäftslösungen entwerfen.', studyProgress: 'Lernfortschritt', questionProgress: 'Fragenfortschritt', mastery: 'Fortschritt', of: 'von', courseCaption: '9 Labs, Contoso Service Resolution Accelerator', insightHeading: 'Konzepte für den produktiven Einsatz.', labFilter: 'Labs nach Bereich filtern', practiceBank: 'Übungsfragen', search: 'Fragen und Konzepte durchsuchen', searchPlaceholder: 'Konzepte durchsuchen …', topicFilter: 'Themenfilter', allTopics: 'Alle Themen', questionList: 'Fragenliste', evidence: 'Belege statt Hörensagen', sourceLead: 'Beginne mit der', sourceEnd: 'maßgeblichen Quelle.', studyGuide: 'Offizieller Prüfungsleitfaden', skillsScope: 'Geprüfte Kompetenzen, Gewichtung und Umfang ↗', learnPath: 'KI-Lösungen für Geschäftsproduktivität entwerfen', learnPathNote: 'Microsoft Learn-Lernpfad ↗', unofficialSet: 'Inoffizielle Übungssammlung', usedCritically: 'Kritisch verwendet ↗', footerNote: 'Für gezieltes Lernen · Rechtliche Angaben vor Veröffentlichung vervollständigen', legalInformation: 'Rechtliche Informationen', disclaimer: 'Haftungsausschluss', privacy: 'Datenschutz', imprint: 'Impressum', closeDialog: 'Dialog schließen', legalNotes: 'Rechtliche Hinweise', labNotes: 'Lab-Kurzbeschreibung', insightNotes: 'Erkenntnis aus dem Kursmaterial', studyArea: 'Diesen Bereich lernen', connectedLabs: '{count} zugehörige Labs', lab: 'Lab', plan: 'Planen', design: 'Entwerfen', deploy: 'Bereitstellen', status: 'Status', learnSource: 'Microsoft Learn-Quelle lesen', confirmed: 'bestätigt', partiallyConfirmed: 'teilweise bestätigt', unofficial: 'Inoffizielle Übung, an Microsoft Learn ausgerichtet', verification: 'Anhand der Dokumentation geprüft; Szenariobewertung, kein Produktausführungstest', labVerification: 'Aus Kursmaterial abgeleitet; mit Microsoft Learn abgleichen', localeWarning: 'Für einige Inhalte fehlt eine aktuelle deutsche Übersetzung. Diese Einträge werden auf Englisch angezeigt; deine Antworten bleiben unverändert.', examUnavailable: 'Eine Prüfung benötigt mindestens 20 eindeutige Fragen.', resourceLabs: 'Architektur-Labs ↗', resourceGuide: 'Lernleitfaden ↗', resourceOfficial: 'Microsoft Learn-Quelle ↗'
  }
};

// Full-label mappings only. Product names and identifiers remain unchanged.
const topicTextDe = {
  'Foundry & Extensibility': 'Foundry und Erweiterbarkeit', 'Copilot Studio Agents': 'Copilot Studio-Agenten',
  'Copilot in Dynamics 365': 'Copilot in Dynamics 365', 'Ecosystem Integration': 'Ökosystemintegration',
  'Monitor & Tune': 'Überwachen und optimieren', 'Responsible AI & Security': 'Verantwortungsvolle KI und Sicherheit',
  'ALM & Environments': 'ALM und Umgebungen', 'AI Strategy & CAF': 'KI-Strategie und CAF',
  'Requirements & Grounding': 'Anforderungen und Grounding', 'ROI & Build-Buy-Extend': 'ROI: Eigenentwicklung, Kauf oder Erweiterung',
  'Testing & Evaluation': 'Tests und Evaluation'
};
uiText.en.fieldGuide = 'FIELD GUIDE';
uiText.de.fieldGuide = 'LERNBEGLEITER';
const outcomeIds = {
  'Assess grounding data quality and apply the Cloud Adoption Framework AI adoption process to enterprise requirements.': 'grounding-caf',
  'Select Microsoft AI platforms and build-buy-extend paths using ROI and total cost of ownership criteria.': 'platform-value',
  'Design Copilot Studio agents and Dynamics 365 AI features that span customer experience, service, and operations.': 'agent-design',
  'Extend multi-agent solutions with Model Context Protocol, Agent2Agent, and Computer Use.': 'extensibility',
  'Evaluate agent quality and design ALM for Copilot Studio, Foundry, custom models, and Dynamics 365 AI.': 'evaluation-alm',
  'Design responsible AI, security, governance, risk, and compliance controls for agents, models, and grounding data.': 'governance'
};
function ui(key, values = {}) {
  return Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, String(value)), uiText[state.language][key] ?? uiText.en[key] ?? key);
}
function t(value) {
  if (state.language !== 'de') return value;
  const key = { 'confirmed': 'confirmed', 'partially confirmed': 'partiallyConfirmed', 'Unofficial practice, Learn-aligned': 'unofficial', 'Documentation-reviewed; scenario judgment, not a product execution test': 'verification', 'Courseware-derived; verify against Microsoft Learn': 'labVerification' }[value];
  return key ? ui(key) : topicTextDe[value] ?? contentDe.outcomes[outcomeIds[value]] ?? value;
}
function localizedQuestion(item, language = state.language) {
  const translated = contentDe.questions[item.id];
  if (language !== 'de' || !translated || translated.revision !== item.revision) return item;
  // Select display fields explicitly; a locale record must never change the answer key.
  return { ...item, question: translated.question, options: translated.options, explanation: translated.explanation,
    ...(item.matchLabels ? { matchLabels: translated.matchLabels } : {}) };
}
function localizedRecord(collection, item) {
  return state.language === 'de' ? { ...item, ...contentDe[collection][item.id] } : item;
}

const legalText = {
  en: {
    disclaimer: { title: 'Disclaimer', html: '<p><strong>Unofficial study project.</strong> This website is an independent, unofficial exam-preparation project.</p><p>It has no affiliation, partnership, authorization, sponsorship, or endorsement from Microsoft, Microsoft Corporation, DumpsBase, or Tertiary Courses. Microsoft, Copilot Studio, Dynamics 365, and AB-100 are trademarks of their respective owners.</p><p>The practice questions are unofficial, Learn-aligned scenarios, not Microsoft-authored exam questions. Lab briefs paraphrase Tertiary Courses C1756 courseware. Source links provide evidence, not endorsement. <strong>No guarantee</strong> is given for accuracy, completeness, currency, availability, error-free operation, or exam success.</p><p>This content is not legal, tax, privacy, professional, or other expert advice. Use this website at your own risk. Verify information independently before relying on it for any binding or public purpose.</p>' },
    privacy: { title: 'Privacy Notice', html: '<p><strong>Controller:</strong> [Operator name or entity]. This project is a static website.</p><p>The application stores study answers and revision backups, lab progress, theme, and language in your browser using <code>localStorage</code>. The current exam, responses, and absolute deadline are stored in <code>sessionStorage</code>.</p><p>The application does not create accounts, transmit answers to its own server, or use its own analytics or tracking services. “Reset progress” deletes study data, backups, lab progress, and the current exam, but keeps theme and language. Browser settings can remove all local data.</p><p>External fonts and the Microsoft badge can connect your browser to their providers. External links open Microsoft Learn, GitHub, DumpsBase, and other source websites. Their own privacy notices apply. Hosting providers may process request logs.</p><p>This notice is not a complete, individualized privacy policy. Complete operator details and review hosting, fonts, logs, and any additional services before public publication.</p>' },
    imprint: { title: 'Legal Notice', html: '<p class="placeholder-notice"><strong>Placeholder: Complete before public publication.</strong></p><p><strong>Provider information under Section 5 DDG</strong></p><p>[Provider name or entity]<br />[Full service address]<br />[Email address]</p><p>This is not a complete provider identification. No VAT ID, commercial register details, or profession-specific information have been provided. Replace all placeholders and obtain an appropriate legal review before publication.</p>' }
  },
  de: {
    disclaimer: { title: 'Haftungsausschluss', html: '<p><strong>Inoffizielles Lernprojekt.</strong> Diese Website ist ein unabhängiges, inoffizielles Projekt zur Prüfungsvorbereitung.</p><p>Es bestehen keine Zugehörigkeit, Partnerschaft, Autorisierung, Förderung oder Empfehlung durch Microsoft, Microsoft Corporation, DumpsBase oder Tertiary Courses. Microsoft, Copilot Studio, Dynamics 365 und AB-100 sind Marken ihrer jeweiligen Inhaber.</p><p>Die Übungsfragen sind inoffizielle, an Microsoft Learn ausgerichtete Szenarien, keine von Microsoft verfassten Prüfungsfragen. Die Lab-Kurzbeschreibungen geben Inhalte des Tertiary Courses C1756-Kursmaterials in eigenen Worten wieder. Quellenlinks dienen als Belege, nicht als Empfehlungen der Anbieter. Es besteht <strong>keine Garantie</strong> für Richtigkeit, Vollständigkeit, Aktualität, Verfügbarkeit, Fehlerfreiheit oder Prüfungserfolg.</p><p>Die Inhalte sind keine Rechts-, Steuer-, Datenschutz-, Berufs- oder sonstige Fachberatung. Die Nutzung erfolgt auf eigenes Risiko. Prüfe Informationen unabhängig, bevor du dich für verbindliche oder öffentliche Zwecke darauf stützt.</p>' },
    privacy: { title: 'Datenschutzhinweis', html: '<p><strong>Verantwortlicher:</strong> [Name oder Organisation des Betreibers]. Dieses Projekt ist eine statische Website.</p><p>Die Anwendung speichert Lernantworten und Revisionssicherungen, Lab-Fortschritt, Darstellung und Sprache mit <code>localStorage</code> in deinem Browser. Die aktuelle Prüfung samt Antworten und absolutem Endzeitpunkt wird in <code>sessionStorage</code> gespeichert.</p><p>Die Anwendung erstellt keine Konten, übermittelt keine Antworten an einen eigenen Server und verwendet keine eigenen Analyse- oder Trackingdienste. „Fortschritt zurücksetzen“ löscht Lerndaten, Sicherungen, Lab-Fortschritt und die aktuelle Prüfung, behält aber Darstellung und Sprache. In den Browsereinstellungen lassen sich sämtliche lokalen Daten entfernen.</p><p>Externe Schriftarten und das Microsoft-Abzeichen können Verbindungen zu deren Anbietern herstellen. Externe Links öffnen Microsoft Learn, GitHub, DumpsBase und weitere Quellwebsites. Dort gelten die jeweiligen Datenschutzhinweise. Hostinganbieter können Zugriffsprotokolle verarbeiten.</p><p>Dieser Hinweis ist keine vollständige, individuell geprüfte Datenschutzerklärung. Vervollständige Betreiberangaben und prüfe Hosting, Schriftarten, Protokolle und zusätzliche Dienste vor öffentlicher Veröffentlichung.</p>' },
    imprint: { title: 'Impressum', html: '<p class="placeholder-notice"><strong>Platzhalter: Vor öffentlicher Veröffentlichung vervollständigen.</strong></p><p><strong>Anbieterangaben gemäß § 5 DDG</strong></p><p>[Name oder Organisation des Anbieters]<br />[Vollständige ladungsfähige Anschrift]<br />[E-Mail-Adresse]</p><p>Dies ist keine vollständige Anbieterkennzeichnung. Umsatzsteuer-ID, Registerangaben und berufsspezifische Angaben wurden nicht bereitgestellt. Ersetze alle Platzhalter und lasse die Angaben vor Veröffentlichung angemessen rechtlich prüfen.</p>' }
  }
};
