const labSlugs = [
  'lab-01-scope-the-contoso-service-operations-agent.md',
  'lab-02-design-identity-channel-and-governance-controls.md',
  'lab-03-create-the-agent-shell-and-instructions.md',
  'lab-04-build-a-request-intake-flow-with-human-review.md',
  'lab-05-create-a-guided-topic-with-variables-and-grounded-answers.md',
  'lab-06-add-an-adaptive-card-and-safe-http-response.md',
  'lab-07-ground-the-agent-in-enterprise-knowledge.md',
  'lab-08-configure-azure-ai-search-and-validate-retrieval.md',
  'lab-09-add-a-ticket-rest-api-tool-from-openapi.md',
  'lab-10-connect-mcp-tools-and-guard-computer-use.md',
  'lab-11-connect-copilot-studio-foundry-and-fabric-specialists.md',
  'lab-12-delegate-a-task-over-a2a.md',
  'lab-13-use-azure-search-evidence-in-a-foundry-prompt.md',
  'lab-14-instrument-the-agent-with-application-insights.md',
  'lab-15-build-a-representative-agent-test-set.md',
  'lab-16-run-evaluation-and-triage-agent-defects.md',
  'lab-17-create-the-agent-solution-and-dependency-inventory.md',
  'lab-18-configure-environment-variables-and-connection-references.md',
  'lab-19-deploy-through-a-power-platform-pipeline.md',
  'lab-20-rehearse-release-monitoring-and-recovery.md'
];
const labs = [
  ['Scope the Contoso Service Operations Agent', 'Define purpose, boundaries, actors, risks, ownership, and fallback behavior.', 'ADR, scenario brief', ['scope', 'architecture'], 1, '9592'],
  ['Design identity, channel, and governance controls', 'Choose identity, Teams/channel strategy, human review, and governance evidence.', 'Governance matrix, ADR extension', ['identity', 'governance'], 1, '9597'],
  ['Create the agent shell and instructions', 'Create a bounded Copilot Studio agent, write instructions, and record a baseline.', 'Agent shell, baseline conversations', ['topics', 'instructions'], 1, '9628'],
  ['Build a request-intake flow with human review', 'Validate inputs, create a Dataverse draft, and route high-risk requests to review.', 'Published flow, six test paths', ['flows', 'HITL'], 1, '9633'],
  ['Create a guided topic with variables and grounded answers', 'Use typed variables, Power Fx validation, grounding, confirmation, and a flow call.', 'Topic, test evidence', ['variables', 'grounding'], 2, '9658'],
  ['Add an Adaptive Card and safe HTTP response', 'Render structured input and map 200, 404, auth, timeout, and 5xx states safely.', 'Card JSON, status topic', ['Adaptive Cards', 'HTTP'], 2, '9708'],
  ['Ground the agent in enterprise knowledge', 'Add approved knowledge, compare a baseline, and test answer boundaries.', 'Knowledge configuration, boundary tests', ['knowledge', 'grounding'], 2, '9684'],
  ['Configure Azure AI Search and validate retrieval', 'Test exact, paraphrased, ambiguous, empty, and stale retrieval scenarios.', 'Retrieval matrix, evidence notes', ['Azure AI Search', 'RAG'], 2, '9739'],
  ['Add a ticket REST API tool from OpenAPI', 'Import an API contract, configure auth, and distinguish lookup from mutation.', 'OpenAPI tool, API test record', ['REST', 'OpenAPI'], 3, '9775'],
  ['Connect MCP tools and guard Computer Use', 'Connect a read-only MCP tool and constrain computer use with isolation and stop rules.', 'MCP activity, safety comparison', ['MCP', 'Computer Use'], 3, '9757'],
  ['Connect Copilot Studio, Foundry, and Fabric specialists', 'Define routing metadata and connect specialized agents with clear boundaries.', 'Routing tests, updated ADR', ['connected agents', 'Foundry', 'Fabric'], 3, '9784'],
  ['Delegate a task over A2A', 'Configure endpoint, auth, context identifiers, timeouts, and server-side traceability.', 'A2A roundtrip, hardening checklist', ['A2A', 'trust boundary'], 3, '9810'],
  ['Use Azure Search evidence in a Foundry prompt', 'Pass retrieved evidence into a structured prompt with complete, insufficient, and conflict states.', 'Prompt version, comparison record', ['Foundry', 'evidence'], 4, '9815'],
  ['Instrument the agent with Application Insights', 'Add custom telemetry, correlation IDs, KQL views, thresholds, and data minimization.', 'KQL view, telemetry scenarios', ['Application Insights', 'KQL'], 4, '9825'],
  ['Build a representative agent test set', 'Create core, robustness, architecture, and boundary cases with observable criteria.', 'Versioned test set', ['test set', 'evaluation'], 4, '9830'],
  ['Run evaluation and triage agent defects', 'Compare a baseline, classify failures, inspect evidence, and regression-test one change.', 'Triage table, before/after evidence', ['evaluation', 'triage'], 4, '9840'],
  ['Create the agent solution and dependency inventory', 'Package agents, flows, tools, prompts, Dataverse objects, and dependencies.', 'Dependency inventory, solution candidate', ['Solutions', 'ALM'], 5, '9850'],
  ['Configure environment variables and connection references', 'Remove hardcoding and verify target-environment configuration and recovery import.', 'Smoke checks, release candidate', ['Environment Variables', 'Connection References'], 5, '9863'],
  ['Deploy through a Power Platform Pipeline', 'Review stages, roles, release diff, managed deployment, and smoke checks.', 'Deployment evidence, Go/Hold decision', ['Pipelines', 'release'], 5, '9845'],
  ['Rehearse release monitoring and recovery', 'Run a release, triage a synthetic 5xx incident, contain it, and rehearse recovery.', 'Runbook, incident timeline, regression case', ['operations', 'recovery'], 5, '9845']
].map((item, index) => ({ id: `lab-${String(index + 1).padStart(2, '0')}`, number: index + 1, title: item[0], summary: item[1], artifacts: item[2].split(', '), concepts: item[3], day: item[4], domain: ({ 1: 'plan', 2: 'design', 3: 'deploy', 4: 'deploy', 5: 'deploy' })[item[4]], sourceUrl: `https://github.com/tertiarycourses/C1760-AB-620-Microsoft-Certified-AI-Agent-Builder-Associate/blob/main/labs/${labSlugs[index]}`, sourceType: 'Tertiary Courses C1760 Courseware', verificationStatus: 'Courseware-derived; verify against Microsoft Learn', checklist: [`Read the lab brief: ${item[0]}`, 'Complete the configuration or design step', 'Run the success and boundary checks', 'Save the named artifact or checkpoint'], relatedQuestionIds: [] }));
