const source = {
  grounding: ['Requirements & Grounding', 'https://learn.microsoft.com/en-us/training/modules/analyze-requirements-ai-powered-business-solutions/'],
  strategy: ['AI Strategy & CAF', 'https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/scenarios/ai/'],
  roi: ['ROI & Build-Buy-Extend', 'https://learn.microsoft.com/en-us/training/modules/evaluate-costs-benefits-ai-powered-business-solution/'],
  d365: ['Copilot in Dynamics 365', 'https://learn.microsoft.com/en-us/dynamics365/copilot/ai-get-started'],
  studio: ['Copilot Studio Agents', 'https://learn.microsoft.com/en-us/microsoft-copilot-studio/'],
  foundry: ['Foundry & Extensibility', 'https://learn.microsoft.com/en-us/azure/ai-foundry/'],
  eco: ['Ecosystem Integration', 'https://learn.microsoft.com/en-us/training/modules/orchestrate-configuration-prebuilt-agents-apps/'],
  monitor: ['Monitor & Tune', 'https://learn.microsoft.com/en-us/training/modules/analyze-monitor-tune-ai-powered-business-solutions/'],
  test: ['Testing & Evaluation', 'https://learn.microsoft.com/en-us/training/modules/manage-testing-ai-powered-business-solutions/'],
  alm: ['ALM & Environments', 'https://learn.microsoft.com/en-us/power-platform/alm/'],
  rai: ['Responsible AI & Security', 'https://learn.microsoft.com/en-us/training/modules/design-responsible-ai-security-governance-risk-management-compliance/']
};
const q = (question, options, answer, explanation, key, extra = {}) => ({ question, options, answer, explanation, topic: source[key][0], source: extra.source || source[key][1], official: false, ...extra });
const community = (question, options, answer, explanation, topic, post, format = 'single', extra = {}) => ({ question, options, answer, explanation, topic, source: `https://thedatacommunity.org/?p=${post}`, sourceType: 'The Data Community practice', verification: 'Cross-checked against Microsoft Learn; unofficial practice content', format, ...extra });

const dumpsbase = [
  q("Contoso listed several foundation models in Microsoft Foundry. Leadership treats that list as proof the solution is ready for production. What should the architect clarify?", ["The catalog is only for open-source models and cannot host Azure-sold models.","Any model visible in the catalog is already approved for customer-facing workloads.","Listing a model in the catalog replaces Responsible AI review.","The catalog is a discovery surface; production use still needs a scenario-specific evaluation quality gate."], 3, "Foundry Models is for discovering, comparing, and deploying candidates. Readiness is a separate GenAIOps evaluation against the business task, safety bar, and ground-truth set.", "foundry", { source: "https://learn.microsoft.com/en-us/azure/foundry/concepts/foundry-models-overview" }),
  q("A service representative must ask a helper to summarize the open case. Overnight invoice exceptions should start when mail arrives, without a chat turn. How should those agents be bounded?", ["A Foundry catalog entry for the chat skill and a Power BI alert for invoices.","Two autonomous agents, because any Dynamics 365 skill must run unattended.","One classic topic for both, because triggers and events are interchangeable.","Interactive task help versus an event-triggered autonomous agent with a defined authority limit."], 3, "Task agents wait for a user turn. Autonomous agents perceive events and act inside scoped permissions, with human approval on high-impact steps.", "studio", { source: "https://learn.microsoft.com/en-us/microsoft-copilot-studio/guidance/autonomous-agents" }),
  q("Sellers at Contoso say “coverage gap” when they mean a custom opportunity column. Copilot in Dynamics 365 Sales keeps querying the wrong field. What should be designed first?", ["A glossary or synonym that maps the business phrase to the Dataverse column used by Copilot.","A public website knowledge source for CRM slang.","A Computer Use session that clicks through the opportunity form.","A new Foundry fine-tune that memorizes every seller nickname."], 0, "Copilot in Sales can be taught organization language through glossary and synonym mappings so chat binds to the correct table columns.", "d365", { source: "https://learn.microsoft.com/en-us/dynamics365/sales/extend-copilot-chat" }),
  q("Match each Contoso building block to the role it should play.", ["4. Foundry custom model","1. Prebuilt Dynamics 365 agent","3. MCP connection","2. Custom Copilot Studio agent"], 0, "Start with in-app agents, extend in Studio when process logic is unique, use MCP for tool and resource contracts, and reserve custom models for gaps the catalog cannot cover.", "eco", { format: "matching", matches: { "0": "D", "1": "A", "2": "C", "3": "B" }, matchLabels: ["A. Turn on a product skill that already fits the process","B. Author topics, tools, and orchestration for a unique flow","C. Expose an external tool or local resource through an open protocol","D. Train or host a model when prebuilt models miss the domain"] }),
  q("After the first production week, Contoso wants session outcomes, engagement, and satisfaction for a Copilot Studio agent. Which starting point matches the platform?", ["Azure DevOps sprint burndown for the maker team.","Copilot Studio analytics and agent-health views that report outcomes such as resolved, escalated, and abandoned.","Export every transcript into a global variable and chart it in Excel.","The Foundry model catalog leaderboard, because it already includes tenant CSAT."], 1, "Studio exposes conversation and autonomous-run analytics so architects can see engagement, outcomes, and satisfaction without building a parallel warehouse first.", "monitor", { source: "https://learn.microsoft.com/en-us/microsoft-copilot-studio/analytics-improve-agent-health" }),
  q("Finance asked for an accounts-payable invoice copilot. Which operating role is appropriate?", ["Store vendor bank details in the chat transcript so the model can “remember” them.","Auto-post every extracted invoice and wire payment the same night.","Draft and classify incoming vendor invoices and pause for a supervisor before posting or unblocking a vendor.","Replace the general ledger with generated journal text."], 2, "Invoice agents extract and draft; supervisors confirm vendors, coding, and exceptions. Autonomous payment or vendor unblocking is outside a safe first envelope.", "d365", { source: "https://learn.microsoft.com/en-us/dynamics365/business-central/payables-agent" }),
  q("Risk wants a Responsible AI dashboard for customer-facing agents. Which content belongs there?", ["Safety and quality evaluations, fairness or drift signals, and completeness of audit trails for model and data changes.","A list of catalog model names with no evaluation scores.","Only token spend and the number of makers with Studio licenses.","The marketing slogan used in the launch email."], 0, "Responsible AI operations track evaluation quality, safety, and auditability. Cost and licensing are useful but they are not the RAI control plane.", "rai"),
  q("A Copilot Studio case agent and an X++ pricing extension must both reach test next month. Which ALM statement is correct?", ["Skip solutions and copy the agent JSON into the AOT project.","Put both artifacts only in the Foundry model catalog.","The Studio agent travels in a Dataverse solution and Power Platform pipeline; the X++ change follows finance and operations ALM, not the same solution package.","Export the X++ project into the Studio canvas and ship both as one unmanaged topic."], 2, "Copilot Studio components are solution-aware on Dataverse. Finance and operations customizations have a separate ALM path. Do not force them into one carrier.", "alm", { source: "https://learn.microsoft.com/en-us/power-platform/alm/overview-alm" }),
  q("Contoso must promote a Studio agent and a Foundry model deployment. Which pipeline split is defensible?", ["SharePoint folder drop as the only release mechanism.","Power Platform pipelines or Build Tools for the solution-aware agent; Foundry and Azure DevOps for model evaluation and deployment.","A single X++ deployable package for both.","Manual copy-paste of connection strings in production."], 1, "Studio ALM rides Power Platform solutions and pipelines. Foundry models and agents need their own evaluation and deployment process. The strategies must align, not collapse.", "alm", { source: "https://learn.microsoft.com/en-us/microsoft-copilot-studio/guidance/alm" }),
  q("A Dynamics 365 Contact Center voice agent should not keep talking when the caller asks for a person or confidence drops. What should the design specify?", ["Restart the same topic until the model invents an answer.","An explicit transfer to a representative with conversation context, not a silent hang-up or a brand-new unauthenticated chat.","Email the transcript to a shared mailbox and end the call.","Switch the channel to SMS without telling the caller."], 1, "Contact Center designs include escalation and transfer paths so humans receive context. Low-confidence loops and dropped sessions are not a handoff.", "d365"),
  q("Grounding files include unpublished contracts. Security asked whether Microsoft Purview or Microsoft Defender is “the AI control.” What should the architect assign?", ["Purview for classification, DLP, and residency of grounding data; Defender for identity and endpoint threat protection. Use both.","Purview only, because prompt attacks are a document-labeling problem.","Defender only, because DLP is not relevant to agents.","Neither; store the contracts in a public website knowledge source."], 0, "Data governance and threat protection are complementary. Grounding access and residency sit with Purview-style controls; runtime and identity attacks sit with Defender-style controls.", "rai"),
  q("The cloud strategy team follows the Cloud Adoption Framework. The Dynamics program follows Success by Design. How should those frameworks be used together?", ["Replace Success by Design with CAF for every Solution Blueprint Review.","Treat them as interchangeable names for the same workshop.","Replace CAF with Success by Design for every Azure landing zone.","CAF for enterprise AI and cloud adoption; Success by Design for Dynamics 365 and Power Platform implementation reviews and blueprints."], 3, "CAF’s AI scenario guides adoption strategy. Success by Design is prescriptive Dynamics implementation guidance. AB-100 expects both, used at different altitudes.", "strategy", { source: "https://learn.microsoft.com/en-us/dynamics365/guidance/implementation-guide/success-by-design" }),
  q("Customer, case, and knowledge records already live in Dataverse. Three agents each copied a weekly CSV into their own prompt library. What should change?", ["Merge the CSVs into one global conversation variable.","Keep Dataverse as the system of record and ground the agents there instead of forking stale extracts.","Move the system of record into the Foundry catalog card.","Disable Dataverse because agents cannot use business-application data."], 1, "Dataverse is the shared store for Dynamics and Copilot Studio artifacts. Copies inside prompts drift and break permissions.", "grounding", { source: "https://learn.microsoft.com/en-us/power-apps/maker/data-platform/data-platform-intro" }),
  q("Finance scored the agent only on first-year license avoidance. What ROI framing should the architect add?", ["Ignore TCO and report only tokens saved in week one.","Horizon-based value: near-term efficiency, mid-term process change, and longer-term options, with total cost of ownership, not license line items alone.","Count every hallucinated answer as a benefit because it is “automation.”","Delay any ROI model until the model catalog has 10,000 entries."], 1, "AB-100 asks for ROI and TCO, including build-buy-extend. Horizon thinking stops a one-year license comparison from hiding change, risk, and operating cost.", "roi"),
  q("Users ask one utterance that needs a policy lookup and a ticket update. Classic trigger phrases keep firing a single topic. Which orchestration change fits?", ["Disable tools so the model answers from memory only.","Add 200 near-duplicate trigger phrases to the same topic.","Replace the agent with a static FAQ page.","Turn on generative orchestration so the planner can chain knowledge, topics, and tools for multi-intent turns."], 3, "Generative orchestration is the default planner for multi-intent chaining. Classic NLU is single-intent and needs more handcrafted topics.", "studio", { source: "https://learn.microsoft.com/en-us/microsoft-copilot-studio/guidance/generative-orchestration" }),
  q("Match each language-understanding option to the situation that justifies it.", ["3. Generative orchestration","2. Azure Conversational Language Understanding","1. Built-in classic NLU"], 0, "Classic NLU fits simple trigger-phrase topics. CLU is for custom, often multilingual or industry models that must stay in sync with topics. Generative orchestration plans across topics, tools, and knowledge.", "studio", { source: "https://learn.microsoft.com/en-us/microsoft-copilot-studio/guidance/language-understanding", format: "matching", matches: { "0": "C", "1": "B", "2": "A" }, matchLabels: ["A. Small topic set with short trigger phrases","B. Custom intents, industry vocabulary, or extra language coverage","C. Multi-intent utterances that should chain tools and knowledge"] }),
  q("A proposed knowledge corpus is complete but six months stale, and row-level permissions are unknown. What is the first grounding decision?", ["Fine-tune a model on the stale extract and skip retrieval.","Connect it immediately because volume is more important than recency.","Upload it to a public website to “open” the permissions.","Treat the source as not ready until freshness, permission trimming, and accuracy are confirmed."], 3, "AB-100 requires reviewing grounding data for accuracy, relevance, timeliness, cleanliness, and availability, including who may see it.", "grounding"),
  q("Contoso can buy a prebuilt service copilot, extend it with Studio topics, or build a Foundry agent from scratch. Which test should drive the choice?", ["Choose whichever demo used the longest prompt.","Whether the prebuilt skill covers the process; extend when a gap is bounded; build custom only when control, data, or model needs exceed extend.","Always build custom so the catalog is unused.","Always buy and never add knowledge or tools."], 1, "Build, buy, or extend is an explicit AB-100 skill. Prefer product capabilities, extend for bounded gaps, and custom-build when the gap is architectural.", "roi"),
  q("Which TWO signals justify creating a custom or small language model instead of a catalog foundation model?", ["The maker prefers a unique model name on a slide.","The catalog already meets quality, safety, and latency bars.","Need for a compact, specialized model with documented cost or latency benefits.","A regulated domain that catalog models cannot meet after evaluation."], [2, 3], "Custom models are justified by unmet quality, domain, cost, or latency needs after evaluation. Preference and already-sufficient catalog models are not.", "foundry", { source: "https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/ab-100", format: "multiple" }),
  q("The AI Center of Excellence asked for a prompt library. What belongs in the standard?", ["One giant system prompt that every agent must paste verbatim, including secrets.","A shared mailbox of unreviewed screenshots.","A rule that prompts may never be tested.","Approved patterns, grounding rules, review owners, and versioning so prompts are reusable assets, not private chat snippets."], 3, "AB-100 includes prompt-library and prompt-engineering guidelines. Treat prompts as governed, versioned assets.", "strategy", { source: "https://learn.microsoft.com/en-us/training/modules/design-overall-ai-strategy-business-solutions/" }),
  q("An internal FAQ over SharePoint should stay inside Microsoft 365 permissions. A multi-step approval that writes to Dataverse will be used by a department. Which platform split fits?", ["Public anonymous Web Chat for both so authentication is skipped.","Foundry Computer Use for both, with no identity.","A Microsoft 365 Copilot declarative helper for the FAQ; a Copilot Studio agent for the governed business process.","Studio only for the FAQ and M365 Copilot only for the Dataverse write path."], 2, "M365 Copilot suits permission-trimmed organizational Q&A. Studio is the path for multi-step business systems, connectors, and enterprise ALM.", "eco", { source: "https://learn.microsoft.com/en-us/microsoft-365/copilot/extensibility/copilot-studio-experience" }),
  q("A line-of-business desktop app has no API. The agent must complete a weekly status form. What extensibility option is in scope?", ["Computer Use against a locked-down machine, with least privilege and confirmation on destructive steps.","Store the UI password in a topic message.","Import the EXE as a Dataverse table.","MCP packet capture on the corporate firewall."], 0, "Computer Use is the Copilot Studio path when the only interface is a UI. Isolation and human confirmation are part of the design, not optional decoration.", "foundry", { source: "https://learn.microsoft.com/en-us/microsoft-copilot-studio/guidance/ai-capabilities" }),
  q("A local diagnostic utility already speaks the open tool protocol for models. How should Copilot Studio consume it?", ["A2A, because every local process is an agent.","Paste the tool output into the system prompt weekly.","An MCP tool connection, after authentication, scope, and DLP review.","Disable DLP so the utility can call any connector."], 2, "MCP standardizes tool and resource access. Discovery does not skip governance of auth, scope, and data policy.", "foundry", { source: "https://learn.microsoft.com/en-us/microsoft-copilot-studio/" }),
  q("A specialized Foundry agent must keep multi-turn diagnosis state while the Studio front door handles the employee. Which collaboration style matches?", ["Agent-to-agent delegation with a clear contract, identity, and correlation across traces.","Ask the employee to retype the case in both agents.","Copy the Foundry weights into a Studio topic variable.","A single stateless HTTP POST that drops history."], 0, "A2A is the open pattern for agent collaboration. The design still needs trust boundaries, observability, and a task contract.", "eco", { source: "https://learn.microsoft.com/en-us/microsoft-copilot-studio/add-agent-agent-to-agent" }),
  q("Inference cost swings wildly because every request hits the largest deployed model. Which AB-100 lever should be designed?", ["Route by the maker’s favorite model name.","A model router that sends each request to the smallest suitable model that still meets the quality bar.","Turn evaluation off so routing has no metrics.","Pin every skill to the most expensive deployment “to be safe.”"], 1, "The study guide includes implementing a model router so cost and quality can be balanced per request type.", "roi", { source: "https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/ab-100" }),
  q("A test set scores high on intent recognition and low on groundedness. What should be inspected first?", ["The number of environments in the tenant.","The footer font on the Adaptive Card.","Whether the agent has a nickname.","Knowledge sources, citations, and whether ungrounded answers are allowed."], 3, "The agent understands the ask but is not sufficiently tied to approved sources. That is a grounding and evaluation problem, not a branding problem.", "test", { source: "https://learn.microsoft.com/en-us/microsoft-copilot-studio/nlu-overview" }),
  q("The solution spans Customer Service cases and Finance invoice status. What should the test strategy include?", ["Only a single-topic trigger-phrase quiz in Studio.","End-to-end scenarios that cross both apps, plus contract tests at each integration boundary.","Only a Foundry catalog browse with no business data.","Skip tests because each app has its own Copilot."], 1, "AB-100 calls for end-to-end tests of AI solutions that use multiple Dynamics 365 apps, not isolated demos.", "test"),
  q("Which environment pattern should carry a Studio agent from first build to production?", ["Separate development, test, and production environments with solutions, environment variables, and connection references.","One production environment that every maker edits live.","No Dataverse database, so solutions cannot be used.","A personal developer environment as the only production host."], 0, "Power Platform ALM needs Dataverse, solutions, and environment-specific configuration. Live-editing production is not an environment strategy.", "alm", { source: "https://learn.microsoft.com/en-us/microsoft-copilot-studio/guidance/alm" }),
  q("Who should be able to change grounding documents and model-tuning sets?", ["No one, because grounding data must be immutable forever.","The agent’s service principal with owner rights on the whole tenant.","A least-privilege group with audit trails; not every maker and not the conversational identity of the agent.","Any authenticated website visitor."], 2, "AB-100 includes access control on grounding data and model tuning, plus audit trails for those changes.", "rai"),
  q("Red-team notes show users can override policy by saying “ignore your instructions.” What belongs in the design?", ["Input checks, grounded refusal, scoped tools, and monitoring for prompt-manipulation attempts.","Granting the agent broader write tools so it can “fight back.”","Disabling transcripts so attacks cannot be reviewed.","A longer marketing disclaimer in the greeting topic only."], 0, "Prompt manipulation is an explicit exam skill. Mitigations are technical and operational, not a banner in the greeting.", "rai", { source: "https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/ab-100" }),
  q("Operations has telemetry but no tuning loop. Which use of that telemetry is correct?", ["Delete low-scoring sessions to improve the average.","Increase autonomy whenever latency rises.","Interpret quality, latency, and failure traces, then change prompts, tools, or models against a baseline.","Archive traces unread so the dashboard stays green."], 2, "Monitoring exists to tune behavior. Vanity cleanup and unearned autonomy are not tuning.", "monitor"),
  q("Product backlog comments say the agent “sounds confident but cites last year’s policy.” Where should that feedback land?", ["In the analysis of agent usage and the knowledge-freshness backlog, then into a tuned source or prompt.","Only as a new trigger phrase that repeats the old policy.","Only in the brand-tone guide.","Ignore qualitative feedback because only token charts matter."], 0, "AB-100 includes analyzing backlog and user feedback of AI and agent usage, not only infrastructure metrics.", "monitor"),
  q("Finance and operations users need in-app help that can see extra procedure manuals. What should the architect propose?", ["Store the manuals only in a maker’s OneDrive.","Disable in-app help and rely on hallway training.","Email the manuals to each user weekly.","The documented process for adding knowledge sources to in-app help and guidance, rather than a shadow chatbot with a copied manual."], 3, "The study guide calls out adding knowledge to in-app help and guidance for Finance and Supply Chain apps.", "d365", { source: "https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/ab-100" }),
  q("Sales Copilot must read a line-of-business pricing API that has no first-party connector. What design is appropriate?", ["Hard-code an API key in a topic message.","Scrape the vendor website with Computer Use for every quote.","A connector or custom connector with least-privilege auth, designed for Copilot in Dynamics 365 Sales—not a password typed in chat.","Turn off authentication because sellers are busy."], 2, "Designing connectors for Copilot in Dynamics 365 Sales is an exam skill. Credentials do not belong in conversation text.", "d365", { source: "https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/ab-100" }),
  q("Which TWO practices belong in the release quality gate for a custom Foundry model?", ["Ship when the catalog page has a logo.","Evaluation against a labeled scenario set for quality and safety.","Compare the candidate to the current production baseline.","Skip human review if latency improved."], [1, 2], "Custom-model validation is an AB-100 testing skill. A catalog page and a single latency win are not a gate.", "test", { source: "https://learn.microsoft.com/en-us/azure/ai-foundry/concepts/observability", format: "multiple" }),
  q("Match each framework or control to the decision it should own.", ["3. Microsoft Purview","2. Success by Design","4. Microsoft Defender","1. Cloud Adoption Framework AI scenario"], 0, "Keep adoption strategy, Dynamics implementation guidance, data governance, and threat protection on the control that is built for that job.", "strategy", { format: "matching", matches: { "0": "C", "1": "B", "2": "D", "3": "A" }, matchLabels: ["A. Enterprise AI adoption and landing-zone alignment","B. Dynamics 365 implementation reviews and living blueprint","C. Classification, DLP, and residency of grounding data","D. Identity and endpoint threat protection"] }),
  q("Which TWO controls must be in the first operating envelope of an autonomous invoice agent?", ["Disabled audit logs to reduce storage.","Unrestricted mailbox and ledger write access on day one.","Grounding in trusted vendor and policy sources.","Human review for posting, vendor creation, or payment."], [2, 3], "High-impact finance actions need human confirmation and trusted data. Broad writes and dark mode logging increase blast radius.", "rai", { source: "https://learn.microsoft.com/en-us/microsoft-copilot-studio/guidance/autonomous-agents", format: "multiple" }),
  q("Business data must later feed other Microsoft AI systems. What organization choice should be made now?", ["Keep a governed, shareable store such as Dataverse or an approved lakehouse with clear ownership, rather than per-agent file dumps.","Block all downstream reuse so every team recaptures the same data.","Give each agent a private spreadsheet as the only copy.","Embed customer rows inside prompt text and call that a platform."], 0, "AB-100 includes organizing business-solution data so it is available to other AI systems without losing ownership or quality.", "grounding")
];

const topicLabMap = {
  'Requirements & Grounding': ['lab-01'],
  'AI Strategy & CAF': ['lab-02'],
  'ROI & Build-Buy-Extend': ['lab-03'],
  'Copilot in Dynamics 365': ['lab-04', 'lab-06'],
  'Copilot Studio Agents': ['lab-04'],
  'Foundry & Extensibility': ['lab-05'],
  'Ecosystem Integration': ['lab-06'],
  'Monitor & Tune': ['lab-07'],
  'Testing & Evaluation': ['lab-07'],
  'ALM & Environments': ['lab-08'],
  'Responsible AI & Security': ['lab-09']
};

const questions = dumpsbase.map((item, index) => ({
  ...item,
  id: index + 1,
  official: item.official || false,
  format: item.format || 'single',
  sourceType: item.sourceType || 'DumpsBase practice',
  verification: item.verification || 'Unofficial practice; verify against Microsoft Learn',
  labIds: item.labIds || topicLabMap[item.topic] || []
}));
